apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: auth-api
  name: auth-api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: auth-api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: auth-api
    spec:
      containers:
      - env:
        - name: DB_HOST
        - value: postgresql
        - name: DB_NAME
        - value: webservices
        - name: DB_USERNAME
        - value: postgres
        - name: DB_PASSWORD
        - value: web-services-g7
        image: tyagipragya/auth-app:latest
        imagePullPolicy: IfNotPresent
        name: auth-api
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
