apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-api
  name: auth-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 5000
  selector:
    io.kompose.service: flask-api
