apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: urlshortener-api
  name: urlshortener-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 5000
  selector:
    io.kompose.service: urlshortener-api
